### PR TITLE
Add header photo to top of webpage

### PR DESCRIPTION
**Pull request by James-BuildBrighton**

### CODE REVIEW

**Comment by James-BuildBrighton** [comment]
having just previewed this, it may be better for the photo to be the same width as the text box below it (A communal workshop and collective of... etc) but i'm not sure how to code that change in. A line break with the blue header above it may also look better

**Comment by matt-oakes** [comment]
I've made some changes to this pull request.

* I've made the hero image you provided be in the background of the text. This is what the website was originally designed for, but no one came forward with a suitable image at the time so it was left as a grey box.
* I have moved all of the images into this repository so they are packaged with the website code and will also be hosted in the same place. This will greatly improve performance and make it easier to maintain the website in the future.

**Comment by matt-oakes** [comment]
@James-BuildBrighton I forgot to say, let me know if you're happy with these changes and I'll make them public. The preview link above will have updated to reflect the changes.

**Comment by James-BuildBrighton** [comment]
@matt-oakes  thanks looks good! only minor things i'd mention would be if possible, to have a line break above the image to separate it from the blue navigation bar at the top (like that box was before), and if there's any way to avoid cutting out the bottom of the image/the bottom of the G in Brighton? I'm aware that may be due to the re-scaling to fit in the text box, so if not, just the line break will be fine and it's good to go

**Pull request merged**
